# Generated by Django 4.2.21 on 2025-06-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moving', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price_per_hour_1_worker',
            new_name='base_price_per_hour',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_per_hour_2_workers',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_per_hour_3_workers',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='destination_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
