# Generated by Django 4.2.21 on 2025-06-11 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moving', '0002_rename_price_per_hour_1_worker_service_base_price_per_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='move_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='move_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 4, 34, 57, 465585, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hours',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='workers',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
